---
language: python
services: docker

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - docker run --rm -it --name "openshift-origin" --net=host --privileged -v /var/run/docker.sock:/var/run/docker.sock openshift/origin start
#  - molecule test
#  - molecule converge
#  - molecule verify
#  - molecule destroy
